// Copyright © 2026 Marcel Joachim Kloubert <marcel@kloubert.dev>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Handshake
	//	*Envelope_Register
	//	*Envelope_RegisterAck
	//	*Envelope_ConnectRequest
	//	*Envelope_ConnectAck
	//	*Envelope_OpenStream
	//	*Envelope_OpenStreamAck
	//	*Envelope_Data
	//	*Envelope_CloseStream
	//	*Envelope_Heartbeat
	//	*Envelope_Disconnect
	//	*Envelope_ErrorMsg
	//	*Envelope_Authenticate
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Envelope) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Envelope) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *Envelope) GetConnectRequest() *ConnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConnectRequest); ok {
			return x.ConnectRequest
		}
	}
	return nil
}

func (x *Envelope) GetConnectAck() *ConnectAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConnectAck); ok {
			return x.ConnectAck
		}
	}
	return nil
}

func (x *Envelope) GetOpenStream() *OpenStream {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OpenStream); ok {
			return x.OpenStream
		}
	}
	return nil
}

func (x *Envelope) GetOpenStreamAck() *OpenStreamAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OpenStreamAck); ok {
			return x.OpenStreamAck
		}
	}
	return nil
}

func (x *Envelope) GetData() *Data {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Envelope) GetCloseStream() *CloseStream {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CloseStream); ok {
			return x.CloseStream
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetDisconnect() *Disconnect {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *Envelope) GetErrorMsg() *ErrorMsg {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ErrorMsg); ok {
			return x.ErrorMsg
		}
	}
	return nil
}

func (x *Envelope) GetAuthenticate() *Authenticate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Authenticate); ok {
			return x.Authenticate
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type Envelope_Register struct {
	Register *Register `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type Envelope_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,3,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type Envelope_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,4,opt,name=connect_request,json=connectRequest,proto3,oneof"`
}

type Envelope_ConnectAck struct {
	ConnectAck *ConnectAck `protobuf:"bytes,5,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type Envelope_OpenStream struct {
	OpenStream *OpenStream `protobuf:"bytes,6,opt,name=open_stream,json=openStream,proto3,oneof"`
}

type Envelope_OpenStreamAck struct {
	OpenStreamAck *OpenStreamAck `protobuf:"bytes,7,opt,name=open_stream_ack,json=openStreamAck,proto3,oneof"`
}

type Envelope_Data struct {
	Data *Data `protobuf:"bytes,8,opt,name=data,proto3,oneof"`
}

type Envelope_CloseStream struct {
	CloseStream *CloseStream `protobuf:"bytes,9,opt,name=close_stream,json=closeStream,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,11,opt,name=disconnect,proto3,oneof"`
}

type Envelope_ErrorMsg struct {
	ErrorMsg *ErrorMsg `protobuf:"bytes,12,opt,name=error_msg,json=errorMsg,proto3,oneof"`
}

type Envelope_Authenticate struct {
	Authenticate *Authenticate `protobuf:"bytes,13,opt,name=authenticate,proto3,oneof"`
}

func (*Envelope_Handshake) isEnvelope_Payload() {}

func (*Envelope_Register) isEnvelope_Payload() {}

func (*Envelope_RegisterAck) isEnvelope_Payload() {}

func (*Envelope_ConnectRequest) isEnvelope_Payload() {}

func (*Envelope_ConnectAck) isEnvelope_Payload() {}

func (*Envelope_OpenStream) isEnvelope_Payload() {}

func (*Envelope_OpenStreamAck) isEnvelope_Payload() {}

func (*Envelope_Data) isEnvelope_Payload() {}

func (*Envelope_CloseStream) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_Disconnect) isEnvelope_Payload() {}

func (*Envelope_ErrorMsg) isEnvelope_Payload() {}

func (*Envelope_Authenticate) isEnvelope_Payload() {}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type ConnectAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAck) Reset() {
	*x = ConnectAck{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAck) ProtoMessage() {}

func (x *ConnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAck.ProtoReflect.Descriptor instead.
func (*ConnectAck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OpenStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStream) Reset() {
	*x = OpenStream{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStream) ProtoMessage() {}

func (x *OpenStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStream.ProtoReflect.Descriptor instead.
func (*OpenStream) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *OpenStream) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

type OpenStreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStreamAck) Reset() {
	*x = OpenStreamAck{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStreamAck) ProtoMessage() {}

func (x *OpenStreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStreamAck.ProtoReflect.Descriptor instead.
func (*OpenStreamAck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *OpenStreamAck) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *OpenStreamAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenStreamAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Data) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CloseStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStream) Reset() {
	*x = CloseStream{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStream) ProtoMessage() {}

func (x *CloseStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStream.ProtoReflect.Descriptor instead.
func (*CloseStream) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *CloseStream) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Disconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ErrorMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	mi := &file_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Authenticate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PassphraseHash []byte                 `protobuf:"bytes,1,opt,name=passphrase_hash,json=passphraseHash,proto3" json:"passphrase_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Authenticate) Reset() {
	*x = Authenticate{}
	mi := &file_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticate) ProtoMessage() {}

func (x *Authenticate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticate.ProtoReflect.Descriptor instead.
func (*Authenticate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Authenticate) GetPassphraseHash() []byte {
	if x != nil {
		return x.PassphraseHash
	}
	return nil
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\tgoconnect\"\xff\x05\n" +
	"\bEnvelope\x124\n" +
	"\thandshake\x18\x01 \x01(\v2\x14.goconnect.HandshakeH\x00R\thandshake\x121\n" +
	"\bregister\x18\x02 \x01(\v2\x13.goconnect.RegisterH\x00R\bregister\x12;\n" +
	"\fregister_ack\x18\x03 \x01(\v2\x16.goconnect.RegisterAckH\x00R\vregisterAck\x12D\n" +
	"\x0fconnect_request\x18\x04 \x01(\v2\x19.goconnect.ConnectRequestH\x00R\x0econnectRequest\x128\n" +
	"\vconnect_ack\x18\x05 \x01(\v2\x15.goconnect.ConnectAckH\x00R\n" +
	"connectAck\x128\n" +
	"\vopen_stream\x18\x06 \x01(\v2\x15.goconnect.OpenStreamH\x00R\n" +
	"openStream\x12B\n" +
	"\x0fopen_stream_ack\x18\a \x01(\v2\x18.goconnect.OpenStreamAckH\x00R\ropenStreamAck\x12%\n" +
	"\x04data\x18\b \x01(\v2\x0f.goconnect.DataH\x00R\x04data\x12;\n" +
	"\fclose_stream\x18\t \x01(\v2\x16.goconnect.CloseStreamH\x00R\vcloseStream\x124\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x14.goconnect.HeartbeatH\x00R\theartbeat\x127\n" +
	"\n" +
	"disconnect\x18\v \x01(\v2\x15.goconnect.DisconnectH\x00R\n" +
	"disconnect\x122\n" +
	"\terror_msg\x18\f \x01(\v2\x13.goconnect.ErrorMsgH\x00R\berrorMsg\x12=\n" +
	"\fauthenticate\x18\r \x01(\v2\x17.goconnect.AuthenticateH\x00R\fauthenticateB\t\n" +
	"\apayload\"*\n" +
	"\tHandshake\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\"/\n" +
	"\bRegister\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"A\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x0eConnectRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"@\n" +
	"\n" +
	"ConnectAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\n" +
	"OpenStream\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\"`\n" +
	"\rOpenStreamAck\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\x04Data\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"*\n" +
	"\vCloseStream\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\"\v\n" +
	"\tHeartbeat\"$\n" +
	"\n" +
	"Disconnect\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"$\n" +
	"\bErrorMsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\fAuthenticate\x12'\n" +
	"\x0fpassphrase_hash\x18\x01 \x01(\fR\x0epassphraseHashB$Z\"github.com/mkloubert/go-connect/pbb\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_messages_proto_goTypes = []any{
	(*Envelope)(nil),       // 0: goconnect.Envelope
	(*Handshake)(nil),      // 1: goconnect.Handshake
	(*Register)(nil),       // 2: goconnect.Register
	(*RegisterAck)(nil),    // 3: goconnect.RegisterAck
	(*ConnectRequest)(nil), // 4: goconnect.ConnectRequest
	(*ConnectAck)(nil),     // 5: goconnect.ConnectAck
	(*OpenStream)(nil),     // 6: goconnect.OpenStream
	(*OpenStreamAck)(nil),  // 7: goconnect.OpenStreamAck
	(*Data)(nil),           // 8: goconnect.Data
	(*CloseStream)(nil),    // 9: goconnect.CloseStream
	(*Heartbeat)(nil),      // 10: goconnect.Heartbeat
	(*Disconnect)(nil),     // 11: goconnect.Disconnect
	(*ErrorMsg)(nil),       // 12: goconnect.ErrorMsg
	(*Authenticate)(nil),   // 13: goconnect.Authenticate
}
var file_proto_messages_proto_depIdxs = []int32{
	1,  // 0: goconnect.Envelope.handshake:type_name -> goconnect.Handshake
	2,  // 1: goconnect.Envelope.register:type_name -> goconnect.Register
	3,  // 2: goconnect.Envelope.register_ack:type_name -> goconnect.RegisterAck
	4,  // 3: goconnect.Envelope.connect_request:type_name -> goconnect.ConnectRequest
	5,  // 4: goconnect.Envelope.connect_ack:type_name -> goconnect.ConnectAck
	6,  // 5: goconnect.Envelope.open_stream:type_name -> goconnect.OpenStream
	7,  // 6: goconnect.Envelope.open_stream_ack:type_name -> goconnect.OpenStreamAck
	8,  // 7: goconnect.Envelope.data:type_name -> goconnect.Data
	9,  // 8: goconnect.Envelope.close_stream:type_name -> goconnect.CloseStream
	10, // 9: goconnect.Envelope.heartbeat:type_name -> goconnect.Heartbeat
	11, // 10: goconnect.Envelope.disconnect:type_name -> goconnect.Disconnect
	12, // 11: goconnect.Envelope.error_msg:type_name -> goconnect.ErrorMsg
	13, // 12: goconnect.Envelope.authenticate:type_name -> goconnect.Authenticate
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Handshake)(nil),
		(*Envelope_Register)(nil),
		(*Envelope_RegisterAck)(nil),
		(*Envelope_ConnectRequest)(nil),
		(*Envelope_ConnectAck)(nil),
		(*Envelope_OpenStream)(nil),
		(*Envelope_OpenStreamAck)(nil),
		(*Envelope_Data)(nil),
		(*Envelope_CloseStream)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Disconnect)(nil),
		(*Envelope_ErrorMsg)(nil),
		(*Envelope_Authenticate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
